.\" Process this file with
.\" groff -man -Tascii winfo.1
.\"
.TH WINFO 1 "winfo-0.4" "" "General Commands Manual"
.SH NAME
winfo \- download and display weather information from wunderground
.SH SYNOPSIS
.B winfo
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-f ]
.RB [ \-o
.BR output ]
.RB [ \-q ]
.RB [ profile ]
.SH DESCRIPTION
.B winfo
is a simple command-line program for downloading and displaying weather
information from wunderground. It stores the downloaded data on disk in order to
allow fast access, and can be used to update the information at regular
intervals using a job scheduler. All data is stored in JSON format, so it can
easily be used by other programs. Information about what data to download and
display is controlled by profiles in the user's home directory.
.SH ARGUMENTS
.TP
.B \-h
Print usage information about the program, then exit.
.TP
.B \-v
Print version information about the program and exit.
.TP
.B \-f
Download new weather data before printing (use
.B \-q
to suppress output).
.TP
.B \-o output
Print the given output string, rather than printing the output string in the
loaded profile.
.TP
.B \-q
Do not print weather information.
.TP
.B profile
Use the given profile to configure what weather information to download. The
profiles are stored in
.I ~/.config/winfo/
by default. If no profile is specified, 'default' is used. See the section below
for more information.
.SH PROFILES
The behavior of this program is controlled by the use of profiles. These
profiles are stored in
.I ~/.config/winfo/
by default. Each profile contains information in the JSON format. Each profile
must include the set of features for downloading, the query location to use, a
valid wunderground developer's key, and an output format. If no profile
is given, then the
.I ~/.config/winfo/default.json
profile is used. Otherwise, the profile
.I ~/.config/winfo/<profile>.json
is used. See the included documentation for more details on profiles.
.SH BUGS
Probably. This hasn't been tested extensively. Report any bugs you find to the
github page
.I http://github.com/velentr/winfo.git
.SH AUTHOR
Copyright (c) 2014 Brian Kubisiak <velentr.rc@gmail.com>
